development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pubfeednotification@gmail.com
  :password: 11Broadway
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pubfeednotification@gmail.com
  :password: ENV['gmail_password']
  :enable_starttls_auto: true